"""empty message

Revision ID: fa0b6ff9f6da
Revises: 
Create Date: 2022-01-26 16:11:34.843106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fa0b6ff9f6da"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("News", sa.Column("category", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("News", "category")
    # ### end Alembic commands ###
